### ISSUE TITLE
White screen then the game shutting down

### ISSUE THREAD

**Issue by NickEtlis** [soupstream/EldenRingStutterFix#3]
When I start a game with new version, I have white screen for 2 sec and the game shutting down :(

**Comment by KingMigi** [comment]
This has been my experience as well.

**Comment by soupstream** [comment]
Can I get your specs? Mainly CPU, GPU, and Windows 10 version (the number in Settings > System > About > Version).

**Comment by NickEtlis** [comment]
Win 10 pro v.1909
GeForce 1080ti
AMD Rizen-7 3800X

**Comment by KingMigi** [comment]
Win 10 pro v1909
GPU: GTX 2080 Super (stock settings)
CPU: i7-8700k (stock settings)
RAM: 32GBs @3200MHz

I also tried disabling any tweaks I made in order to improve performance, such as the Stack Overflow tweak and all that, removed all mods and mod loader, removed all traces of ReShade, ensured there wasn't some conflict with MSI Afterburner or RTSS, Steam Overlay is disabled, etc. I tried a buttload of things, but I just couldn't get it to work. White screen for two seconds, then client crashes.

**Comment by SugarKnights** [comment]
I have the same problem.
and my win 10 system is also 1909.
Could it be because of system problems?

**Comment by soupstream** [comment]
It seems the win10 1909 version of d3d12.dll isn't compatible with the mod for whatever reason. I'll look into a fix.

**Comment by SugarKnights** [comment]
thank you very much,can't wait to enjoy this great work！！！
Thank you again for doing it for us frame dropping players！！！

**Comment by SugarKnights** [comment]
I upgraded my Win10 version to 21H2,and now i can enter the game.
lol lol lol

**Comment by KingMigi** [comment]
Hello. I just wanted to ask if there had been any progress on this particular issue? No rush, I very much appreciate what you're doing. Just wanted to ask.

I would just update my Windows, but for some reason, despite being a legitimate copy of Windows, my ability to update became broken months ago, and I've never been able to find a fix.

**Comment by SugarKnights** [comment]
Hi, you can go to the official website of Windows to download the update.
This should help you upgrade to the latest version, which is version 21H2.
Hope this helps you.

**Comment by soupstream** [comment]
I've published version 1.0.3 with a fix.
