### ISSUE TITLE
Since this patches D3D12, can we move this into our global D3D12 config so we don't need to disable EAC?

### ISSUE THREAD

**Issue by jazir5** [soupstream/EldenRingStutterFix#5]
D3D12 is installed at the OS level, if the DLL was to be replaced there, would that eliminate the need to replace the DLL in the game?

**Comment by cmhamiche** [comment]
I'm no expert but:
- EAC like most anti-cheats software reads the memory content so it doesn't matter, it will detect the modification anyway.
- Replacing the system's dll isn't a good idea since nobody knows what would happen to other apps that uses DirectX12.
- Windows will prioritize the folder's content instead of using the system's dll so it's a perfectly viable solution for injection.

**Comment by jazir5** [comment]
Just trying to find a way around disabling EAC so its still possible to play online

**Comment by soupstream** [comment]
My understanding is the same as cmhamiche's. Unfortunately there's no good way around disabling EAC if you want to use mods.
